# Generated by Django 4.2.4 on 2023-08-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Employee', 'employee'), ('Client', 'client')], default='employee', max_length=10),
        ),
    ]
